//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketDCR2.BWSD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HudsonCRMEntities2 : DbContext
    {
        public HudsonCRMEntities2()
            : base("name=HudsonCRMEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_DailySaleReport> tbl_DailySaleReport { get; set; }
        public virtual DbSet<tbl_DailySaleReport_Temp> tbl_DailySaleReport_Temp { get; set; }
        public virtual DbSet<tbl_DistributerToBricksMasterDataTemp> tbl_DistributerToBricksMasterDataTemp { get; set; }
        public virtual DbSet<tbl_SalesDataBrickWise> tbl_SalesDataBrickWise { get; set; }
        public virtual DbSet<tbl_UploadDistributerToBricksMaster> tbl_UploadDistributerToBricksMaster { get; set; }
        public virtual DbSet<tbl_UploadExcelSalesData> tbl_UploadExcelSalesData { get; set; }
        public virtual DbSet<tbl_SalesStockTemp> tbl_SalesStockTemp { get; set; }
        public virtual DbSet<tbl_SalesCustTemp> tbl_SalesCustTemp { get; set; }
        public virtual DbSet<tbl_SalesInvTemp> tbl_SalesInvTemp { get; set; }
    }
}
