//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketDCR2.BWSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesCustTemp
    {
        public int PK_ID { get; set; }
        public Nullable<int> FK_ExcelID { get; set; }
        public string DSTBID { get; set; }
        public string CUSTID { get; set; }
        public string CT { get; set; }
        public string CUSTNAME { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string TOWNID { get; set; }
        public string TOWN { get; set; }
        public int UserId { get; set; }
        public string FlagStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string StatusRemarks { get; set; }
        public Nullable<int> RecordNo { get; set; }
    }
}
