//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketDCR2.BWSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DailySaleReport_Temp
    {
        public int DSRID { get; set; }
        public string AddedID { get; set; }
        public string I { get; set; }
        public Nullable<int> DistributorID { get; set; }
        public string DistributorCode { get; set; }
        public string DistributorName { get; set; }
        public string SaleFlag { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public string ClientType { get; set; }
        public Nullable<int> BrickID { get; set; }
        public string BrickCode { get; set; }
        public string BrickName { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string TeamName { get; set; }
        public string PackCode { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SkuId { get; set; }
        public string Description { get; set; }
        public string StockBatch { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string Units { get; set; }
        public string Bonus { get; set; }
        public string Discount { get; set; }
        public string ValueNp { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> CreateDateSystem { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string flag { get; set; }
    }
}
