//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketDCR2.BWSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DistributerToBricksMasterDataTemp
    {
        public int ID { get; set; }
        public Nullable<int> DTBMID { get; set; }
        public string Region { get; set; }
        public string SubRegion { get; set; }
        public string District { get; set; }
        public string CityCode { get; set; }
        public string City { get; set; }
        public string DSTBID { get; set; }
        public string Distributor { get; set; }
        public string DSTBCode { get; set; }
        public string TeamName { get; set; }
        public string BrickCode { get; set; }
        public string BrickName { get; set; }
        public string TM_SAS_ID { get; set; }
        public string Share { get; set; }
        public string CRM_TM_IDS { get; set; }
        public Nullable<bool> ProcessStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreateDateSystem { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string flag { get; set; }
    }
}
