//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketDCR2.BWSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesInvTemp
    {
        public int PK_ID { get; set; }
        public Nullable<int> FK_ExcelID { get; set; }
        public string DISBID { get; set; }
        public string INVOICENO { get; set; }
        public string INVOICEDATE { get; set; }
        public string CUSTID { get; set; }
        public string BRICKID { get; set; }
        public string PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public string BATCH { get; set; }
        public string RATE { get; set; }
        public string QUANTITY { get; set; }
        public string BONUS { get; set; }
        public string DISCOUNT { get; set; }
        public string NETAMOUNT { get; set; }
        public string REASON { get; set; }
        public int UserId { get; set; }
        public string FlagStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string StatusRemarks { get; set; }
        public Nullable<int> RecordNo { get; set; }
    }
}
