//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketDCR2.BWSD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SalesDataBrickWise
    {
        public int ID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public string DistributorName { get; set; }
        public Nullable<int> BrickId { get; set; }
        public string BrickName { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SkuId { get; set; }
        public string Description { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string TeamName { get; set; }
        public string units { get; set; }
        public string valuetp { get; set; }
        public string system { get; set; }
        public Nullable<System.DateTime> MonthOfSalesData { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
