<div class="row" >
  <div class="col-md-4" id="col1">
    <div class="divcol">
      <label ID="Label1" name="Label1" ClientIDMode="Static" runat="server"></label>
    </div>
    <div id="col11">
      <select id="ddl1" name="ddl1" class="form-control form-control">
        <option value="-1">Select...</option>
      </select>
    </div>

  </div>
  <div class="col-md-4" id="col2">
    <div class="divcol">
      <label ID="Label2" name="Label1" ClientIDMode="Static" runat="server"></label>
    </div>
    <div id="col22">
      <select id="ddl2" name="ddl2" class="form-control form-control">
        <option value="-1">Select...</option>
      </select>
    </div>
  </div>
  <div class="col-md-4" id="col3">
    <div class="divcol">
      <label ID="Label3" name="Label1" ClientIDMode="Static" runat="server"></label>
    </div>
    <div id="col33">
      <select id="ddl3" name="ddl3" class="form-control form-control">
        <option value="-1">Select...</option>
      </select>
    </div>
  </div>
  <div class="col-md-4" id="col4">
    <div class="divcol">
      <label ID="Label4" name="Label1" ClientIDMode="Static" runat="server"></label>
    </div>
    <div id="col44">
      <select id="ddl4" name="ddl4" class="form-control form-control">
        <option value="-1">Select...</option>
      </select>
    </div>

  </div>
  <div class="col-md-4" id="col5">
    <div class="divcol">
      <label ID="Label5" name="Label1" ClientIDMode="Static" runat="server"></label>
    </div>
    <div id="col55">
      <select id="ddl5" name="ddl5" class="form-control form-control">
        <option value="-1">Select...</option>
      </select>
    </div>
  </div>
  <div class="col-md-4" id="col6">
    <div class="divcol">
      <label ID="Label6" name="Label1" ClientIDMode="Static" runat="server"></label>
    </div>
    <div id="col66">
      <select id="ddl6" name="ddl6" class="form-control form-control">
        <option value="-1">Select...</option>
      </select>
    </div>
  </div>
</div>