//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCRMServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class app_smsReceived
    {
        public int pk_app_smsReceivedID { get; set; }
        public string DoctorID { get; set; }
        public Nullable<System.DateTime> visitDate { get; set; }
        public string MessageType { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string P1 { get; set; }
        public string P2 { get; set; }
        public string P3 { get; set; }
        public string R1 { get; set; }
        public string R2 { get; set; }
        public string R3 { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S4 { get; set; }
        public string S5 { get; set; }
        public string S6 { get; set; }
        public Nullable<int> SQ1 { get; set; }
        public Nullable<int> SQ2 { get; set; }
        public Nullable<int> SQ3 { get; set; }
        public Nullable<int> SQ4 { get; set; }
        public Nullable<int> SQ5 { get; set; }
        public Nullable<int> SQ6 { get; set; }
        public string G1 { get; set; }
        public string G2 { get; set; }
        public string G3 { get; set; }
        public string G4 { get; set; }
        public string G5 { get; set; }
        public string G6 { get; set; }
        public Nullable<int> GQ1 { get; set; }
        public Nullable<int> GQ2 { get; set; }
        public Nullable<int> GQ3 { get; set; }
        public Nullable<int> GQ4 { get; set; }
        public Nullable<int> GQ5 { get; set; }
        public Nullable<int> GQ6 { get; set; }
        public string JV { get; set; }
        public string VShift { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Note { get; set; }
    }
}
