//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCRMServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.DoctorsOfSpoes = new HashSet<DoctorsOfSpo>();
        }
    
        public long DoctorId { get; set; }
        public int DesignationId { get; set; }
        public string DoctorCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public int Gender { get; set; }
        public bool KOL { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string MobileNumber1 { get; set; }
        public string MobileNumber2 { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> TiemStamp { get; set; }
    
        public virtual ICollection<DoctorsOfSpo> DoctorsOfSpoes { get; set; }
    }
}
