//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCRMServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.DoctorsOfSpoes = new HashSet<DoctorsOfSpo>();
        }
    
        public long EmployeeId { get; set; }
        public int DesignationId { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string LoginId { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public int Gender { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> ManagerId { get; set; }
        public Nullable<int> DepotId { get; set; }
        public Nullable<bool> IsSample { get; set; }
        public Nullable<int> pree_days { get; set; }
    
        public virtual ICollection<DoctorsOfSpo> DoctorsOfSpoes { get; set; }
    }
}
