//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCRMServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSku
    {
        public int SkuId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> PackSizeid { get; set; }
        public Nullable<int> StrengthId { get; set; }
        public Nullable<int> FormId { get; set; }
        public string SkuCode { get; set; }
        public string SkuName { get; set; }
        public bool IsActive { get; set; }
        public decimal DistributorPrice { get; set; }
        public decimal TradePrice { get; set; }
        public decimal RetailPrice { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
