//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketDCR2.IMSBrickUploaderRelation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IMSBrick_Tem
    {
        public int ID { get; set; }
        public Nullable<int> Fk_FileID { get; set; }
        public string Territory { get; set; }
        public string CRM_Territory { get; set; }
        public string BrickCode { get; set; }
        public string BrickName { get; set; }
        public Nullable<int> DistricID { get; set; }
        public string DistricName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Remarks { get; set; }
        public string System { get; set; }
        public string Flag { get; set; }
    
        public virtual Tbl_UploadFilePath_IMSBrick Tbl_UploadFilePath_IMSBrick { get; set; }
    }
}
