//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketDCR2.IMSBrickUploaderRelation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UploadFilePath_IMSBrick
    {
        public Tbl_UploadFilePath_IMSBrick()
        {
            this.Tbl_IMSBrick_Tem = new HashSet<Tbl_IMSBrick_Tem>();
        }
    
        public int PkID { get; set; }
        public string ExecuteFileName { get; set; }
        public Nullable<long> EmpID { get; set; }
        public Nullable<bool> ProcessStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatDate { get; set; }
        public Nullable<System.DateTime> ProcessCompleteTime { get; set; }
        public string FileName { get; set; }
        public string System { get; set; }
    
        public virtual ICollection<Tbl_IMSBrick_Tem> Tbl_IMSBrick_Tem { get; set; }
    }
}
